language: java
sudo: true
dist: xenial
jdk:
  - oraclejdk8
dist: trusty
before_install:
  - chmod +x mvnw
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends postgresql-common
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sudo service postgresql start 11
