language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
service:
    - postgresql
addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-11
before_install:
  - chmod +x mvnw
before_script:
    - psql -c "CREATE DATABASE toledoBank;" -U postgres