language: java
sudo: true
jdk:
  - oraclejdk11
dist: xenial
before_install:
  - chmod +x mvnw
install:
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends postgresql-common
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sudo service postgresql start 11
before_script:
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/11/main
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - export PATH="/usr/lib/postgresql/11/bin:$PATH"
  - sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'root'"
  - export PGPASSWORD='root'
  - psql -c 'CREATE DATABASE toledoBank;' -U postgres -P
after_success:
  - bash <(curl -s https://codecov.io/bash)