language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
service:
    - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_install:
  - sudo apt-get update
  - sudo apt-get install
  - chmod +x mvnw
before_script:
    - psql -c "CREATE DATABASE toledoBank;" -U postgres