language: java
sudo: true
jdk:
  - oraclejdk11
dist: xenial
before_install:
  - chmod +x mvnw
install:
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends postgresql-common
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sudo service postgresql start 11
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres