language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
before_install:
  - chmod +x mvnw
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo service postgresql restart
before_script:
  - psql --version
  - psql -c 'create database travis_ci_test;' -U postgres
services:
    - postgresql
