language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
services:
    - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
    - postgresql-server-dev-11
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
before_install:
  - sudo apt-get update
  - sudo apt-get install
  - chmod +x mvnw
before_script:
      - psql -c 'create database travis_ci_test;' -U postgres
