language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
service:
    - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
before_install:
  - sudo apt-get update
  - sudo apt-get install
  - chmod +x mvnw
before_script:
    - psql -c "CREATE DATABASE toledoBank;" -U postgres