language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
services:
    - postgresql
addons:
  postgresql: "11.6"
  apt:
    packages:
    - postgresql-11.6
    - postgresql-client-11.6
    - postgresql-server-dev-11.6
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
before_install:
  - chmod +x mvnw
before_script:
      - psql -c 'create database travis_ci_test;' -U postgres
